"""Shared strategy enums for v2."""

from enum import Enum


class AMDPhase(Enum):
    ACCUMULATION = "ACCUMULATION"
    MANIPULATION = "MANIPULATION"
    DISTRIBUTION = "DISTRIBUTION"


class BreakType(Enum):
    FBOS = "FBOS"
    RBOS = "RBOS"
    NONE = "NONE"


class BiasDirection(Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


class SessionLabel(Enum):
    ASIA = "ASIA"
    LONDON = "LONDON"
    NEW_YORK = "NEW_YORK"
    OFF_HOURS = "OFF_HOURS"


class DOLType(Enum):
    EQH_EQL = "EQH_EQL"
    SESSION_HL = "SESSION_HL"
    PDH_PDL = "PDH_PDL"
    PWH_PWL = "PWH_PWL"
    SMT_OPEN = "SMT_OPEN"
    STRUCT_SWING = "STRUCT_SWING"
    INTERNAL_DOL = "INTERNAL_DOL"


class ZoneRole(Enum):
    OB = "OB"
    SMT = "SMT"
    INTERNAL = "INTERNAL"


class OBState(Enum):
    VALID_OB = "VALID_OB"
    SMT_TRAP = "SMT_TRAP"
    DEPLETED = "DEPLETED"


class EntryModel(Enum):
    FBOS = "FBOS"
    AGGRESSIVE_SWEEP = "AGGRESSIVE_SWEEP"
    MITIGATION = "MITIGATION"
    SMT_REACTION = "SMT_REACTION"


class EntryTrigger(Enum):
    AGGRESSIVE_SWEEP = "AGGRESSIVE_SWEEP"
    SWEEP_CLOSE_AGGRESSIVE = "SWEEP_CLOSE_AGGRESSIVE"
    POST_SWEEP_CONFIRMATION = "POST_SWEEP_CONFIRMATION"
    OB_TAP_PLUS_M5_BOS = "OB_TAP_PLUS_M5_BOS"
    LIMIT_ON_ZONE = "LIMIT_ON_ZONE"


class InvalidationReason(Enum):
    DOL_ALREADY_HIT = "DOL_ALREADY_HIT"
    COUNTER_HTF_BIAS = "COUNTER_HTF_BIAS"
    OB_ALREADY_TAPPED = "OB_ALREADY_TAPPED"
    MOMENTUM_NOT_SHARP = "MOMENTUM_NOT_SHARP"
    RETURNED_TO_RANGE = "RETURNED_TO_RANGE"
    PROTECTED_LEVEL_SWEEPED = "PROTECTED_LEVEL_SWEEPED"
    HTF_POI_INSIDE_SL = "HTF_POI_INSIDE_SL"
    NEWS_WINDOW_BLOCK = "NEWS_WINDOW_BLOCK"
    OPPOSING_HTF_BOS = "OPPOSING_HTF_BOS"


class TradeState(Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    BE_MOVED = "BE_MOVED"
    PARTIAL_TP_HIT = "PARTIAL_TP_HIT"
    CLOSED = "CLOSED"
    INVALIDATED = "INVALIDATED"
